"""Bundle data.json + i18n/*.json into content.js so index.html also works when
opened directly from disk (file://), where browsers block fetch().
Run after every edit to data.json or i18n/*.json:  python tools/build_content.py
The live site (http/https) still fetches data.json directly."""
import json, pathlib, sys
root = pathlib.Path(__file__).resolve().parent.parent
src = {"data": "data.json", "en": "i18n/en.json", "pl": "i18n/pl.json"}
bundle = {}
for key, rel in src.items():
    p = root / rel
    try:
        bundle[key] = json.loads(p.read_text(encoding="utf-8"))
    except FileNotFoundError:
        if key == "pl":
            continue
        sys.exit(f"missing {rel}")
    except json.JSONDecodeError as e:
        sys.exit(f"invalid JSON in {rel}: {e}")
payload = json.dumps(bundle, ensure_ascii=True, separators=(",", ":")).replace("</", "<\\/")
(root / "content.js").write_text(
    "/* GENERATED by tools/build_content.py - do not edit. Used only for file:// previews. */\n"
    "window.__CONTENT__ = " + payload + ";\n", encoding="utf-8")
# Cache-busting: stamp ?v=<hash> on local CSS/JS references so browsers never mix old and new files.
import hashlib, re
def _h(name):
    return hashlib.sha1((root / name).read_bytes()).hexdigest()[:10]
for page in ("index.html", "case.html"):
    fp = root / page
    if not fp.exists():
        continue
    html = fp.read_text(encoding="utf-8")
    for asset in ("style.css", "app.js", "theme-init.js"):
        html = re.sub(r'((?:href|src)=")' + re.escape(asset) + r'(\?v=[0-9a-f]+)?"', lambda m: m.group(1) + asset + "?v=" + _h(asset) + '"', html)
    fp.write_text(html, encoding="utf-8")
print(f"content.js written ({(root / 'content.js').stat().st_size:,} bytes)")
